const { MongoClient } = require('mongodb');

const MONGODB_URI = 'mongodb://localhost:27017';
const MONGODB_DB = 'crane_management_db';

async function seedData() {
  const client = new MongoClient(MONGODB_URI);
  
  try {
    await client.connect();
    console.log('Connected to MongoDB');
    
    const db = client.db(MONGODB_DB);
    const cranesCollection = db.collection('cranes');
    
    // Sample crane data - 20 diverse cranes for UAE operations
    const sampleCranes = [
      // Mobile Cranes
      {
        name: 'Liebherr LTM 1100-4.2',
        code: 'CRANE001',
        type: 'Mobile Crane',
        capacity: '100 tons',
        boomLength: '60m',
        location: 'Dubai Marina',
        status: 'Available',
        operator: 'Ahmed Al Mansouri',
        lastMaintenance: new Date('2024-01-15'),
        nextMaintenance: new Date('2024-07-15'),
        purchasePrice: 2500000,
        dailyRate: 15000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Grove GMK 3055',
        code: 'CRANE002',
        type: 'Mobile Crane',
        capacity: '55 tons',
        boomLength: '42m',
        location: 'Abu Dhabi Downtown',
        status: 'In Use',
        operator: 'Mohammed Al Qassimi',
        lastMaintenance: new Date('2024-02-20'),
        nextMaintenance: new Date('2024-08-20'),
        purchasePrice: 1800000,
        dailyRate: 12000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Terex AC 1000',
        code: 'CRANE003',
        type: 'All Terrain Crane',
        capacity: '1000 tons',
        boomLength: '84m',
        location: 'Sharjah Industrial',
        status: 'Maintenance',
        operator: 'Omar Al Suwaidi',
        lastMaintenance: new Date('2024-03-10'),
        nextMaintenance: new Date('2024-09-10'),
        purchasePrice: 8500000,
        dailyRate: 45000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Demag CC 2800-1',
        code: 'CRANE004',
        type: 'Crawler Crane',
        capacity: '600 tons',
        boomLength: '126m',
        location: 'Ras Al Khaimah Port',
        status: 'Available',
        operator: 'Khalid Al Zaabi',
        lastMaintenance: new Date('2024-01-30'),
        nextMaintenance: new Date('2024-07-30'),
        purchasePrice: 6500000,
        dailyRate: 35000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Kato NK-500E-V',
        code: 'CRANE005',
        type: 'Truck Mounted Crane',
        capacity: '50 tons',
        boomLength: '35m',
        location: 'Fujairah Free Zone',
        status: 'Available',
        operator: 'Hassan Al Falasi',
        lastMaintenance: new Date('2024-02-15'),
        nextMaintenance: new Date('2024-08-15'),
        purchasePrice: 1200000,
        dailyRate: 8000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Tower Cranes
      {
        name: 'Potain MDT 178',
        code: 'CRANE006',
        type: 'Tower Crane',
        capacity: '18 tons',
        boomLength: '60m',
        location: 'Dubai Hills Estate',
        status: 'In Use',
        operator: 'Youssef Al Maktoum',
        lastMaintenance: new Date('2024-03-01'),
        nextMaintenance: new Date('2024-09-01'),
        purchasePrice: 3200000,
        dailyRate: 18000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Liebherr 150 EC-H',
        code: 'CRANE007',
        type: 'Tower Crane',
        capacity: '15 tons',
        boomLength: '50m',
        location: 'Abu Dhabi Global Market',
        status: 'Available',
        operator: 'Abdullah Al Nahyan',
        lastMaintenance: new Date('2024-02-10'),
        nextMaintenance: new Date('2024-08-10'),
        purchasePrice: 2800000,
        dailyRate: 16000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comansa 21LC 290',
        code: 'CRANE008',
        type: 'Tower Crane',
        capacity: '21 tons',
        boomLength: '70m',
        location: 'Sharjah University City',
        status: 'In Use',
        operator: 'Saeed Al Qasimi',
        lastMaintenance: new Date('2024-03-15'),
        nextMaintenance: new Date('2024-09-15'),
        purchasePrice: 3500000,
        dailyRate: 20000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Specialized Cranes
      {
        name: 'Liebherr LR 13000',
        code: 'CRANE009',
        type: 'Crawler Crane',
        capacity: '3000 tons',
        boomLength: '156m',
        location: 'Jebel Ali Port',
        status: 'Available',
        operator: 'Rashid Al Maktoum',
        lastMaintenance: new Date('2024-01-20'),
        nextMaintenance: new Date('2024-07-20'),
        purchasePrice: 15000000,
        dailyRate: 75000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Demag CC 8800-1',
        code: 'CRANE010',
        type: 'Crawler Crane',
        capacity: '1600 tons',
        boomLength: '126m',
        location: 'Mina Zayed Port',
        status: 'Maintenance',
        operator: 'Zayed Al Nahyan',
        lastMaintenance: new Date('2024-03-05'),
        nextMaintenance: new Date('2024-09-05'),
        purchasePrice: 12000000,
        dailyRate: 60000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Grove GMK 6400',
        code: 'CRANE011',
        type: 'Mobile Crane',
        capacity: '400 tons',
        boomLength: '84m',
        location: 'Al Ain Industrial City',
        status: 'Available',
        operator: 'Tariq Al Qaydi',
        lastMaintenance: new Date('2024-02-25'),
        nextMaintenance: new Date('2024-08-25'),
        purchasePrice: 5500000,
        dailyRate: 30000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Terex AC 350/6',
        code: 'CRANE012',
        type: 'All Terrain Crane',
        capacity: '350 tons',
        boomLength: '60m',
        location: 'Umm Al Quwain',
        status: 'In Use',
        operator: 'Majid Al Ali',
        lastMaintenance: new Date('2024-01-25'),
        nextMaintenance: new Date('2024-07-25'),
        purchasePrice: 4200000,
        dailyRate: 25000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Kato NK-800E-V',
        code: 'CRANE013',
        type: 'Truck Mounted Crane',
        capacity: '80 tons',
        boomLength: '42m',
        location: 'Ajman Free Zone',
        status: 'Available',
        operator: 'Sultan Al Nuaimi',
        lastMaintenance: new Date('2024-02-28'),
        nextMaintenance: new Date('2024-08-28'),
        purchasePrice: 1800000,
        dailyRate: 12000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Potain MDT 189',
        code: 'CRANE014',
        type: 'Tower Crane',
        capacity: '20 tons',
        boomLength: '65m',
        location: 'Dubai Creek Harbour',
        status: 'In Use',
        operator: 'Hamdan Al Maktoum',
        lastMaintenance: new Date('2024-03-08'),
        nextMaintenance: new Date('2024-09-08'),
        purchasePrice: 3800000,
        dailyRate: 22000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Liebherr 200 EC-H',
        code: 'CRANE015',
        type: 'Tower Crane',
        capacity: '20 tons',
        boomLength: '55m',
        location: 'Abu Dhabi Corniche',
        status: 'Available',
        operator: 'Mohammed Al Falahi',
        lastMaintenance: new Date('2024-02-18'),
        nextMaintenance: new Date('2024-08-18'),
        purchasePrice: 3200000,
        dailyRate: 19000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Comansa 21LC 320',
        code: 'CRANE016',
        type: 'Tower Crane',
        capacity: '21 tons',
        boomLength: '75m',
        location: 'Sharjah Al Qasimiya',
        status: 'In Use',
        operator: 'Ahmed Al Qasimi',
        lastMaintenance: new Date('2024-03-12'),
        nextMaintenance: new Date('2024-09-12'),
        purchasePrice: 4000000,
        dailyRate: 24000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Liebherr LTM 1500-8.1',
        code: 'CRANE017',
        type: 'Mobile Crane',
        capacity: '500 tons',
        boomLength: '72m',
        location: 'Dubai World Central',
        status: 'Available',
        operator: 'Saif Al Maktoum',
        lastMaintenance: new Date('2024-01-28'),
        nextMaintenance: new Date('2024-07-28'),
        purchasePrice: 6800000,
        dailyRate: 38000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Grove GMK 7450',
        code: 'CRANE018',
        type: 'Mobile Crane',
        capacity: '450 tons',
        boomLength: '78m',
        location: 'Abu Dhabi Airport',
        status: 'Maintenance',
        operator: 'Khalifa Al Nahyan',
        lastMaintenance: new Date('2024-03-18'),
        nextMaintenance: new Date('2024-09-18'),
        purchasePrice: 5800000,
        dailyRate: 32000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Terex AC 500-2',
        code: 'CRANE019',
        type: 'All Terrain Crane',
        capacity: '500 tons',
        boomLength: '66m',
        location: 'Sharjah International Airport',
        status: 'Available',
        operator: 'Abdulrahman Al Qasimi',
        lastMaintenance: new Date('2024-02-22'),
        nextMaintenance: new Date('2024-08-22'),
        purchasePrice: 4800000,
        dailyRate: 28000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Demag CC 2500-1',
        code: 'CRANE020',
        type: 'Crawler Crane',
        capacity: '500 tons',
        boomLength: '96m',
        location: 'Fujairah Port',
        status: 'In Use',
        operator: 'Hamad Al Sharqi',
        lastMaintenance: new Date('2024-01-30'),
        nextMaintenance: new Date('2024-07-30'),
        purchasePrice: 5200000,
        dailyRate: 30000,
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ];

    // Clear existing cranes
    await cranesCollection.deleteMany({});
    console.log('Cleared existing cranes');

    // Insert sample cranes
    await cranesCollection.insertMany(sampleCranes);
    console.log(`Inserted ${sampleCranes.length} sample cranes`);

    console.log('Sample data seeded successfully!');
    console.log('You can now start the application and see the sample cranes.');
    console.log('Crane types included:');
    console.log('- Mobile Cranes (5 cranes)');
    console.log('- Tower Cranes (3 cranes)');
    console.log('- Crawler Cranes (3 cranes)');
    console.log('- All Terrain Cranes (3 cranes)');
    console.log('- Truck Mounted Cranes (2 cranes)');
    console.log('- Specialized Heavy Cranes (4 cranes)');

  } catch (error) {
    console.error('Error seeding data:', error);
  } finally {
    await client.close();
  }
}

seedData(); 