const { MongoClient } = require('mongodb');

const MONGODB_URI = 'mongodb://localhost:27017';
const MONGODB_DB = 'medical_shop';

async function seedData() {
  const client = new MongoClient(MONGODB_URI);
  
  try {
    await client.connect();
    console.log('Connected to MongoDB');
    
    const db = client.db(MONGODB_DB);
    const medicinesCollection = db.collection('medicines');
    
    // Sample medicine data - 50 diverse medicines
    const sampleMedicines = [
      // Pain Relief Medicines
      {
        name: 'Paracetamol 500mg',
        code: 'MED001',
        quantity: 150,
        purchasePrice: 0.30,
        sellingPrice: 0.60,
        expiryDate: new Date('2025-12-31'),
        batchNo: 'BATCH001',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Ibuprofen 400mg',
        code: 'MED002',
        quantity: 120,
        purchasePrice: 0.45,
        sellingPrice: 0.90,
        expiryDate: new Date('2025-10-15'),
        batchNo: 'BATCH002',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Aspirin 100mg',
        code: 'MED003',
        quantity: 200,
        purchasePrice: 0.25,
        sellingPrice: 0.50,
        expiryDate: new Date('2025-08-20'),
        batchNo: 'BATCH003',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Diclofenac 50mg',
        code: 'MED004',
        quantity: 80,
        purchasePrice: 0.80,
        sellingPrice: 1.60,
        expiryDate: new Date('2025-06-30'),
        batchNo: 'BATCH004',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Naproxen 250mg',
        code: 'MED005',
        quantity: 60,
        purchasePrice: 1.20,
        sellingPrice: 2.40,
        expiryDate: new Date('2025-09-15'),
        batchNo: 'BATCH005',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Antibiotics
      {
        name: 'Amoxicillin 250mg',
        code: 'MED006',
        quantity: 100,
        purchasePrice: 1.50,
        sellingPrice: 3.00,
        expiryDate: new Date('2024-08-20'),
        batchNo: 'BATCH006',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Amoxicillin 500mg',
        code: 'MED007',
        quantity: 75,
        purchasePrice: 2.00,
        sellingPrice: 4.00,
        expiryDate: new Date('2024-09-25'),
        batchNo: 'BATCH007',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Ciprofloxacin 250mg',
        code: 'MED008',
        quantity: 50,
        purchasePrice: 2.50,
        sellingPrice: 5.00,
        expiryDate: new Date('2024-10-30'),
        batchNo: 'BATCH008',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Azithromycin 250mg',
        code: 'MED009',
        quantity: 40,
        purchasePrice: 3.00,
        sellingPrice: 6.00,
        expiryDate: new Date('2024-11-15'),
        batchNo: 'BATCH009',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Doxycycline 100mg',
        code: 'MED010',
        quantity: 65,
        purchasePrice: 1.80,
        sellingPrice: 3.60,
        expiryDate: new Date('2024-12-20'),
        batchNo: 'BATCH010',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Gastrointestinal Medicines
      {
        name: 'Omeprazole 20mg',
        code: 'MED011',
        quantity: 90,
        purchasePrice: 1.20,
        sellingPrice: 2.40,
        expiryDate: new Date('2025-06-30'),
        batchNo: 'BATCH011',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Ranitidine 150mg',
        code: 'MED012',
        quantity: 110,
        purchasePrice: 0.90,
        sellingPrice: 1.80,
        expiryDate: new Date('2025-07-15'),
        batchNo: 'BATCH012',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lansoprazole 30mg',
        code: 'MED013',
        quantity: 70,
        purchasePrice: 1.60,
        sellingPrice: 3.20,
        expiryDate: new Date('2025-08-10'),
        batchNo: 'BATCH013',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Metronidazole 400mg',
        code: 'MED014',
        quantity: 85,
        purchasePrice: 1.10,
        sellingPrice: 2.20,
        expiryDate: new Date('2025-09-05'),
        batchNo: 'BATCH014',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cimetidine 200mg',
        code: 'MED015',
        quantity: 95,
        purchasePrice: 0.70,
        sellingPrice: 1.40,
        expiryDate: new Date('2025-10-20'),
        batchNo: 'BATCH015',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Allergy Medicines
      {
        name: 'Cetirizine 10mg',
        code: 'MED016',
        quantity: 130,
        purchasePrice: 0.60,
        sellingPrice: 1.20,
        expiryDate: new Date('2025-09-15'),
        batchNo: 'BATCH016',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Loratadine 10mg',
        code: 'MED017',
        quantity: 115,
        purchasePrice: 0.75,
        sellingPrice: 1.50,
        expiryDate: new Date('2025-10-25'),
        batchNo: 'BATCH017',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Fexofenadine 120mg',
        code: 'MED018',
        quantity: 55,
        purchasePrice: 1.40,
        sellingPrice: 2.80,
        expiryDate: new Date('2025-11-10'),
        batchNo: 'BATCH018',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Chlorpheniramine 4mg',
        code: 'MED019',
        quantity: 140,
        purchasePrice: 0.40,
        sellingPrice: 0.80,
        expiryDate: new Date('2025-12-05'),
        batchNo: 'BATCH019',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Diphenhydramine 25mg',
        code: 'MED020',
        quantity: 100,
        purchasePrice: 0.55,
        sellingPrice: 1.10,
        expiryDate: new Date('2025-01-15'),
        batchNo: 'BATCH020',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Cardiovascular Medicines
      {
        name: 'Amlodipine 5mg',
        code: 'MED021',
        quantity: 45,
        purchasePrice: 2.20,
        sellingPrice: 4.40,
        expiryDate: new Date('2025-02-20'),
        batchNo: 'BATCH021',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Lisinopril 10mg',
        code: 'MED022',
        quantity: 50,
        purchasePrice: 1.90,
        sellingPrice: 3.80,
        expiryDate: new Date('2025-03-25'),
        batchNo: 'BATCH022',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Metoprolol 50mg',
        code: 'MED023',
        quantity: 60,
        purchasePrice: 1.70,
        sellingPrice: 3.40,
        expiryDate: new Date('2025-04-30'),
        batchNo: 'BATCH023',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atenolol 50mg',
        code: 'MED024',
        quantity: 55,
        purchasePrice: 1.50,
        sellingPrice: 3.00,
        expiryDate: new Date('2025-05-15'),
        batchNo: 'BATCH024',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Losartan 50mg',
        code: 'MED025',
        quantity: 40,
        purchasePrice: 2.80,
        sellingPrice: 5.60,
        expiryDate: new Date('2025-06-20'),
        batchNo: 'BATCH025',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Diabetes Medicines
      {
        name: 'Metformin 500mg',
        code: 'MED026',
        quantity: 120,
        purchasePrice: 0.80,
        sellingPrice: 1.60,
        expiryDate: new Date('2025-07-10'),
        batchNo: 'BATCH026',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Metformin 850mg',
        code: 'MED027',
        quantity: 90,
        purchasePrice: 1.10,
        sellingPrice: 2.20,
        expiryDate: new Date('2025-08-15'),
        batchNo: 'BATCH027',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Gliclazide 80mg',
        code: 'MED028',
        quantity: 70,
        purchasePrice: 1.30,
        sellingPrice: 2.60,
        expiryDate: new Date('2025-09-20'),
        batchNo: 'BATCH028',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Glimepiride 1mg',
        code: 'MED029',
        quantity: 50,
        purchasePrice: 1.60,
        sellingPrice: 3.20,
        expiryDate: new Date('2025-10-25'),
        batchNo: 'BATCH029',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Pioglitazone 15mg',
        code: 'MED030',
        quantity: 35,
        purchasePrice: 2.40,
        sellingPrice: 4.80,
        expiryDate: new Date('2025-11-30'),
        batchNo: 'BATCH030',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Respiratory Medicines
      {
        name: 'Salbutamol 100mcg',
        code: 'MED031',
        quantity: 80,
        purchasePrice: 1.80,
        sellingPrice: 3.60,
        expiryDate: new Date('2025-12-05'),
        batchNo: 'BATCH031',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Theophylline 200mg',
        code: 'MED032',
        quantity: 45,
        purchasePrice: 2.10,
        sellingPrice: 4.20,
        expiryDate: new Date('2025-01-10'),
        batchNo: 'BATCH032',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Montelukast 10mg',
        code: 'MED033',
        quantity: 60,
        purchasePrice: 2.70,
        sellingPrice: 5.40,
        expiryDate: new Date('2025-02-15'),
        batchNo: 'BATCH033',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Budesonide 200mcg',
        code: 'MED034',
        quantity: 40,
        purchasePrice: 3.20,
        sellingPrice: 6.40,
        expiryDate: new Date('2025-03-20'),
        batchNo: 'BATCH034',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Ipratropium 20mcg',
        code: 'MED035',
        quantity: 55,
        purchasePrice: 2.90,
        sellingPrice: 5.80,
        expiryDate: new Date('2025-04-25'),
        batchNo: 'BATCH035',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Psychiatric Medicines
      {
        name: 'Sertraline 50mg',
        code: 'MED036',
        quantity: 30,
        purchasePrice: 3.50,
        sellingPrice: 7.00,
        expiryDate: new Date('2025-05-30'),
        batchNo: 'BATCH036',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Fluoxetine 20mg',
        code: 'MED037',
        quantity: 35,
        purchasePrice: 3.20,
        sellingPrice: 6.40,
        expiryDate: new Date('2025-06-05'),
        batchNo: 'BATCH037',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Escitalopram 10mg',
        code: 'MED038',
        quantity: 25,
        purchasePrice: 4.10,
        sellingPrice: 8.20,
        expiryDate: new Date('2025-07-10'),
        batchNo: 'BATCH038',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Venlafaxine 75mg',
        code: 'MED039',
        quantity: 20,
        purchasePrice: 4.80,
        sellingPrice: 9.60,
        expiryDate: new Date('2025-08-15'),
        batchNo: 'BATCH039',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Bupropion 150mg',
        code: 'MED040',
        quantity: 15,
        purchasePrice: 5.20,
        sellingPrice: 10.40,
        expiryDate: new Date('2025-09-20'),
        batchNo: 'BATCH040',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Vitamins and Supplements
      {
        name: 'Vitamin C 500mg',
        code: 'MED041',
        quantity: 200,
        purchasePrice: 0.40,
        sellingPrice: 0.80,
        expiryDate: new Date('2025-10-25'),
        batchNo: 'BATCH041',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Vitamin D3 1000IU',
        code: 'MED042',
        quantity: 180,
        purchasePrice: 0.60,
        sellingPrice: 1.20,
        expiryDate: new Date('2025-11-30'),
        batchNo: 'BATCH042',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Vitamin B12 1000mcg',
        code: 'MED043',
        quantity: 150,
        purchasePrice: 0.70,
        sellingPrice: 1.40,
        expiryDate: new Date('2025-12-05'),
        batchNo: 'BATCH043',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Calcium Carbonate 500mg',
        code: 'MED044',
        quantity: 160,
        purchasePrice: 0.50,
        sellingPrice: 1.00,
        expiryDate: new Date('2025-01-10'),
        batchNo: 'BATCH044',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Iron Sulfate 325mg',
        code: 'MED045',
        quantity: 120,
        purchasePrice: 0.80,
        sellingPrice: 1.60,
        expiryDate: new Date('2025-02-15'),
        batchNo: 'BATCH045',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Topical Medicines
      {
        name: 'Betamethasone Cream 0.1%',
        code: 'MED046',
        quantity: 80,
        purchasePrice: 2.50,
        sellingPrice: 5.00,
        expiryDate: new Date('2025-03-20'),
        batchNo: 'BATCH046',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Mupirocin Ointment 2%',
        code: 'MED047',
        quantity: 60,
        purchasePrice: 3.20,
        sellingPrice: 6.40,
        expiryDate: new Date('2025-04-25'),
        batchNo: 'BATCH047',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Clotrimazole Cream 1%',
        code: 'MED048',
        quantity: 90,
        purchasePrice: 1.80,
        sellingPrice: 3.60,
        expiryDate: new Date('2025-05-30'),
        batchNo: 'BATCH048',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Hydrocortisone Cream 1%',
        code: 'MED049',
        quantity: 70,
        purchasePrice: 2.10,
        sellingPrice: 4.20,
        expiryDate: new Date('2025-06-05'),
        batchNo: 'BATCH049',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Neomycin Ointment 0.5%',
        code: 'MED050',
        quantity: 50,
        purchasePrice: 2.80,
        sellingPrice: 5.60,
        expiryDate: new Date('2025-07-10'),
        batchNo: 'BATCH050',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];
    
    // Clear existing data
    await medicinesCollection.deleteMany({});
    console.log('Cleared existing medicines');
    
    // Insert sample data
    const result = await medicinesCollection.insertMany(sampleMedicines);
    console.log(`Inserted ${result.insertedCount} sample medicines`);
    
    console.log('Sample data seeded successfully!');
    console.log('You can now start the application and see the sample medicines.');
    console.log('Categories included:');
    console.log('- Pain Relief (5 medicines)');
    console.log('- Antibiotics (5 medicines)');
    console.log('- Gastrointestinal (5 medicines)');
    console.log('- Allergy (5 medicines)');
    console.log('- Cardiovascular (5 medicines)');
    console.log('- Diabetes (5 medicines)');
    console.log('- Respiratory (5 medicines)');
    console.log('- Psychiatric (5 medicines)');
    console.log('- Vitamins & Supplements (5 medicines)');
    console.log('- Topical Medicines (5 medicines)');
    
  } catch (error) {
    console.error('Error seeding data:', error);
  } finally {
    await client.close();
  }
}

// Run the seed function
seedData(); 